title: "MHHRI"
description: "Mental Health and Human Rights Info"
baseurl: "/hhri"
url: "https://henkpb.github.io"
collections_dir: "content"
collections:
  news:
    output: true
  theme_gbv:
    output: true
  theme_children:
    output: true
exclude:
  - "README.md"
  - "*/README.md"
